import Providers from '@/components/Providers'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head>
        <meta name='referrer' content='no-referrer-when-downgrade' />
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
